apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: sops-secret
stringData:
    username: ENC[AES256_GCM,data:g+cpQg==,iv:1XrYcmkh7fufIJDAWJd9qP50O7K9JFjCgXMZy2KBIqQ=,tag:EJHmG4zlmlEd2JNK5uEkTQ==,type:str]
    password: ENC[AES256_GCM,data:wIvxJxG8hESEp8k0OggwzRuxPnSvRGaAedpYGHb7LPb/6cQ33desQ/Cr,iv:raGjIvhoHLUuIeKUeVHpGJRb0bm4FxCT6msXMvcJ3U0=,tag:flyWuTxtti4O3qvImXrZvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-08T06:32:45Z"
    mac: ENC[AES256_GCM,data:npXlGwGZmu3rCgN3I74Oy7mU3m12N6fWlG7ijDsEBUa2ivkm5SnWoHXk2EGaPw8slOCVLBiq5wz2Ro8RpyDgCt2tTdxVVcV4taHbubJ9ZwjwI9MHM4xz8DpowZX6njVURuUgxApLKKNgb0vprRhRYHDygAsmWCxGwiIzFc0mp3w=,iv:o9YU3giW7RSlfl9dNbfNEjf8wsrEbSyWF4OBp+ZjphI=,tag:DhecjhujfG3bhQsXvwiHVA==,type:str]
    pgp:
        - created_at: "2023-10-08T06:32:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcDMA8Y54zwbc8q5AQv+KzkwTOhiRoIYTz2qzlIYe6dVgRRri3qZlb8RTAB/2zBp
            9Ud3BeDmQRu52qZ0G8JN37xOy4t7XA8QXPEGAn7vSPRKKm9fMBq805nXkm2/CDX8
            btqikKHIh4qvVSzubJxPV54CDyz1+WqaAaJpvXFnF3U1wmPlbcLsGWvEtTcHJnP3
            EZykcTUgTLdz1c8nWNq43NEQTPh2EzkcY1nPVs+pprYW7DQm2ZxvGPH8LQeGb1DY
            1YqIFNVHhFZc5Ay6WJZdS8ajojN4dUzTA4p+dKHd1jN5BuT4Vxs2f9b8EUOlhqKQ
            o/XbM4WZXdO1UTVDwJkOaGubaoFdGQC55nk6C6thN6k888CIeivCqCVmXC7pHOfp
            vQcbNGBwXacfiSQduuVxFWVpnBbfpFXwdlimSm5btODAlSnlXkKlbvA+RPdz+hDy
            pZqI63DbwQT0W3wONXuKbJ1NX/4TFaOYzQze1Yk8YAwqft4XvXxLEZlJXq7hq4g8
            spZcTYjFuUo88Xe+BdqS0lEB4vDAMg0ldmgoz8vPybfK3OegW8auIBDoN0V18o1h
            RWPzWVs7Xdh1JPfSGdyslGVQSh5KK/NAn4YBF4jm104zm5wDVBsiA2RzRzJNVKVg
            sPg=
            =/6A2
            -----END PGP MESSAGE-----
          fp: BCE2DDD20AD01EA195258EFC7C763F0629387D2D
    encrypted_regex: ^^(data|stringData)$
    version: 3.8.0
